### ISSUE TITLE
docviewer-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/docviewer-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Viewing the app's documentation (Some of my best comedic material, these bug reports)

**Comment by Flohack74** [comment]
@balcy will be the new maintainer here. A warm welcome ;)
