### ISSUE TITLE
Document viewer does not open document when called from other app

### ISSUE THREAD

**Issue by TischlerWilly** [ubports/docviewer-app#2]
When open a file out of an other app the docviewer-app don't get the data.
A short example :
Document viewer is not open
I read a mail in dekko
I will open the pdf that comes with the mail
I click open the pdf with the document viewer
The program starts, but don't open the pdf
I have to go back to dekko and
Say open pdf again
Now I can read the pdf in document viewer

**Comment by Flohack74** [comment]
Confirmed, I got the same problem. @sverzegnassi any ideas about this?

**Comment by sverzegnassi** [comment]
Yes, it's about that patch I wrote more than an year ago but Canonical never released it on the store. Fortunately, the patch has been already merged in trunk[1]. Tomorrow I'll fix the git support for docviewer-app and will release an update in the OpenStore. ;)

[1] https://github.com/ubports/docviewer-app/commit/3b3aff696b185978952ff533ad59eba959b979c6

**Comment by TischlerWilly** [comment]
Today I have updated to Version 2.1.369re from Open Store.
But with these release is can not open from other apps at all.
When Document Viewer is not open before I get en error MSG. (Fehler Datei ist nicht vorhanden)
If Document Viewer is open before noinothing happened.
There is also no Foulder "Documents/Imported" on my phone, like in the release notes of this version

**Comment by Flohack74** [comment]
Are you sure you got it from Openstore? I still dont see it there...

**Comment by sverzegnassi** [comment]
DocViewer has been released a few hours ago, however I decided to unpublish it until I don't investigate on the issue.
At a first sight, it seems a regression caused by me; therefore, I would like to apologize for the inconvenience.

**Comment by TischlerWilly** [comment]
I have found the mistake :-)
I have create the folder Documents/Imported by the Program Dateiverwaltung.
Now the issue is not there anymore.
So the problem is, that Document Viewer can not create the Folder when the folder don't exist jet.

**Comment by TischlerWilly** [comment]
The code in this directory has the last commit in April 2017. So I thing it is not the aktualest code of the program.? Is it possible to upload the code of the version witch was for a short time in the Open Store available?
For me this version works very well, until I have created the missed foulder.
I think is is it worth to get the actual code and try to find someone who know how to fix this last step of the stairs and make it somehow available on Open Store again.

**Comment by sverzegnassi** [comment]
@TischlerWilly, we'll proceed with a PR for ubports/docviewer-app in the following days. Current code of DocViewer is available here: https://github.com/sverzegnassi/docviewer-app

Bugfix for issue #2 is now available in OpenStore (Document Viewer v. 2.1.370). DocViewer can now create the ~/Documents/Imported path if it doesn't exists. Sorry if it took so long, but I had some issue with uploading packages on OpenStore in the last few days. Brain and I managed to fix it just an hour ago.

**Comment by TischlerWilly** [comment]
Oh, great ! Very thanks ! That are great news :-)
