### ISSUE TITLE
wrong colors in libreoffice documents

### ISSUE THREAD

**Issue by balcy** [ubports/docviewer-app#30]
I've seen that at least for odg and odt documents (likely for other libreoffice formats as well) the colors are not displayed correctly on the phone. 

Green is correct, but the other colors are switched.

here is a screenshot from the current xenial version on BQ Aquaris 4.5:
![colors_odt](https://user-images.githubusercontent.com/848115/44308089-2c249780-a3af-11e8-9210-bd5595a28bf7.jpeg)

the corresponding PDF is displayed correctly in docviewer
![colors_pdf](https://user-images.githubusercontent.com/848115/44308097-45c5df00-a3af-11e8-94c8-f6f6894802c8.jpeg)

**Comment by Flohack74** [comment]
lol wtf

**Comment by balcy** [comment]
this was known before, maybe just a switch of color channels.. not sure how it was in vivid (have mostly read text documents with only black / white)

**Comment by Flohack74** [comment]
Can you send me the test documents plz via Telegram? thx!

**Comment by Flohack74** [comment]
Seems I got it
![grafik](https://user-images.githubusercontent.com/16186470/44360968-bf97be80-a4bc-11e8-8400-9fa291f1c275.png)
